[package]
name = "font-fallback"
version = "0.1.0"
edition = "2021"

[dependencies]
objc2-core-foundation = "0.3.1"
objc2-core-text = "0.3.1"
thiserror = "2"

sbr-util = { git = "https://github.com/afishhh/subrandr.git", rev = "050e094753cc9b2a01ca975e7a9752a336ba6345" }
